package be.hepl.benbear.iobrep;

public enum PacketId {

    LOGIN,
    LOGIN_RESPONSE,
    GET_CONTAINERS,
    GET_CONTAINERS_RESPONSE,
    CONTAINER_OUT,
    CONTAINER_OUT_RESPONSE,
    CONTAINER_OUT_END,
    CONTAINER_OUT_END_RESPONSE,
    BOAT_ARRIVED,
    BOAT_ARRIVED_RESPONSE,
    CONTAINER_IN,
    CONTAINER_IN_RESPONSE,
    CONTAINER_IN_END,
    CONTAINER_IN_END_RESPONSE,
    INVALID_SESSION_RESPONSE,
    LOGOUT,
    ;

}
